import { describe, expect, test, vi } from "vite-plus/test";
import { createSessionRecord } from "../shared/session-grid-contract";
import {
  PreviousSessionHistory,
  type PreviousSessionHistoryEntry,
} from "./previous-session-history";

vi.mock("vscode", () => ({}));

describe("PreviousSessionHistory", () => {
  test("should expose generated-name metadata and clear autogenerated aliases", async () => {
    const generatedSession = createSessionRecord(1, 0);
    const renamedSession = {
      ...createSessionRecord(2, 1),
      alias: "Fix prev sessions modal",
    };
    const update = vi.fn(async () => undefined);
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(generatedSession, "history-1", {
            terminalTitle: "Codex / generated session",
          }),
          createHistoryEntry(renamedSession, "history-2", {
            terminalTitle: "Codex / renamed session",
          }),
        ]),
        update,
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      { historyId: "history-1", isGeneratedName: true },
      { historyId: "history-2", isGeneratedName: false },
    ]);

    await expect(history.removeGeneratedNames()).resolves.toBe(1);

    expect(history.getItems()).toMatchObject([{ historyId: "history-2", isGeneratedName: false }]);
    expect(update).toHaveBeenCalledTimes(1);
  });

  test("should keep legacy word aliases when clearing auto names", async () => {
    const legacyWordAliasSession = {
      ...createSessionRecord(1, 0),
      alias: "Vale",
    };
    const update = vi.fn(async () => undefined);
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(legacyWordAliasSession, "history-1", {
            terminalTitle: "Codex / legacy alias",
          }),
        ]),
        update,
      },
    } as never);

    await expect(history.removeGeneratedNames()).resolves.toBe(0);

    expect(history.getItems()).toMatchObject([{ historyId: "history-1", isGeneratedName: false }]);
    expect(update).not.toHaveBeenCalled();
  });

  test("should show the stored terminal title as the primary title for legacy auto-named sessions", () => {
    const generatedSession = createSessionRecord(1, 0);
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(generatedSession, "history-1", {
            primaryTitle: undefined,
            terminalTitle: "Codex / recent sessions polish",
          }),
        ]),
        update: vi.fn(async () => undefined),
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      {
        historyId: "history-1",
        primaryTitle: "Codex / recent sessions polish",
        terminalTitle: undefined,
      },
    ]);
  });

  test("should preserve the user title while keeping the terminal title for legacy renamed sessions", () => {
    const renamedSession = {
      ...createSessionRecord(1, 0),
      title: "Bug Fix",
    };
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(renamedSession, "history-1", {
            primaryTitle: undefined,
            terminalTitle: "Codex / recent sessions polish",
          }),
        ]),
        update: vi.fn(async () => undefined),
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      {
        historyId: "history-1",
        primaryTitle: "Bug Fix",
        terminalTitle: "Codex / recent sessions polish",
      },
    ]);
  });

  test("should prefer the terminal title for Claude and Codex history entries", () => {
    const renamedSession = {
      ...createSessionRecord(1, 0),
      title: "Bug Fix",
    };
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(renamedSession, "history-1", {
            agentIcon: "claude",
            primaryTitle: "Bug Fix",
            terminalTitle: "Claude / recent sessions polish",
          }),
        ]),
        update: vi.fn(async () => undefined),
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      {
        historyId: "history-1",
        primaryTitle: "Claude / recent sessions polish",
        terminalTitle: undefined,
      },
    ]);
  });

  test("should keep the terminal title primary for newly archived Claude and Codex history entries", () => {
    const renamedSession = {
      ...createSessionRecord(1, 0),
      title: "Bug Fix",
    };
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(renamedSession, "history-1", {
            agentIcon: "codex",
            primaryTitle: "Codex / recent sessions polish",
            terminalTitle: undefined,
          }),
        ]),
        update: vi.fn(async () => undefined),
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      {
        historyId: "history-1",
        primaryTitle: "Codex / recent sessions polish",
        terminalTitle: undefined,
      },
    ]);
  });

  test("should prefer the stored T3 thread title over the generic session title in history", () => {
    const t3Session = createSessionRecord(1, 0, {
      kind: "t3",
      t3: {
        projectId: "project-1",
        serverOrigin: "http://127.0.0.1:3774",
        threadId: "thread-1",
        workspaceRoot: "/tmp/project",
      },
      title: "T3 Code",
    });
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(t3Session, "history-1", {
            agentIcon: "t3",
            primaryTitle: "Project Overview",
            terminalTitle: undefined,
          }),
        ]),
        update: vi.fn(async () => undefined),
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      {
        historyId: "history-1",
        primaryTitle: "Project Overview",
        terminalTitle: undefined,
      },
    ]);
  });

  test("should hide terminal history entries that have neither a user title nor a terminal title", () => {
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [createHistoryEntry(createSessionRecord(1, 0), "history-1")]),
        update: vi.fn(async () => undefined),
      },
    } as never);

    expect(history.getItems()).toEqual([]);
  });
});

function createHistoryEntry(
  sessionRecord: ReturnType<typeof createSessionRecord>,
  historyId: string,
  sidebarItemOverrides: Partial<PreviousSessionHistoryEntry["sidebarItem"]> = {},
): PreviousSessionHistoryEntry {
  return {
    closedAt: "2026-03-24T10:00:00.000Z",
    historyId,
    sessionRecord,
    sidebarItem: {
      activity: "idle",
      alias: sessionRecord.alias,
      column: sessionRecord.column,
      isFocused: false,
      isRunning: false,
      isVisible: false,
      row: sessionRecord.row,
      sessionId: sessionRecord.sessionId,
      shortcutLabel: "⌘⌥1",
      ...sidebarItemOverrides,
    },
  };
}
