import { describe, expect, test, vi } from "vite-plus/test";
import { createSessionRecord } from "../shared/session-grid-contract";
import {
  PreviousSessionHistory,
  type PreviousSessionHistoryEntry,
} from "./previous-session-history";

vi.mock("vscode", () => ({}));

describe("PreviousSessionHistory", () => {
  test("should expose generated-name metadata and clear autogenerated aliases", async () => {
    const generatedSession = createSessionRecord(1, 0);
    const renamedSession = {
      ...createSessionRecord(2, 1),
      alias: "Fix prev sessions modal",
    };
    const update = vi.fn(async () => undefined);
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [
          createHistoryEntry(generatedSession, "history-1"),
          createHistoryEntry(renamedSession, "history-2"),
        ]),
        update,
      },
    } as never);

    expect(history.getItems()).toMatchObject([
      { historyId: "history-1", isGeneratedName: true },
      { historyId: "history-2", isGeneratedName: false },
    ]);

    await expect(history.removeGeneratedNames()).resolves.toBe(1);

    expect(history.getItems()).toMatchObject([{ historyId: "history-2", isGeneratedName: false }]);
    expect(update).toHaveBeenCalledTimes(1);
  });

  test("should keep legacy word aliases when clearing auto names", async () => {
    const legacyWordAliasSession = {
      ...createSessionRecord(1, 0),
      alias: "Vale",
    };
    const update = vi.fn(async () => undefined);
    const history = new PreviousSessionHistory({
      workspaceState: {
        get: vi.fn(() => [createHistoryEntry(legacyWordAliasSession, "history-1")]),
        update,
      },
    } as never);

    await expect(history.removeGeneratedNames()).resolves.toBe(0);

    expect(history.getItems()).toMatchObject([{ historyId: "history-1", isGeneratedName: false }]);
    expect(update).not.toHaveBeenCalled();
  });
});

function createHistoryEntry(
  sessionRecord: ReturnType<typeof createSessionRecord>,
  historyId: string,
): PreviousSessionHistoryEntry {
  return {
    closedAt: "2026-03-24T10:00:00.000Z",
    historyId,
    sessionRecord,
    sidebarItem: {
      activity: "idle",
      alias: sessionRecord.alias,
      column: sessionRecord.column,
      isFocused: false,
      isRunning: false,
      isVisible: false,
      row: sessionRecord.row,
      sessionId: sessionRecord.sessionId,
      shortcutLabel: "⌘⌥1",
    },
  };
}
