import type { ComponentType } from "react";
import {
  IconApi,
  IconArchiveFilled,
  IconBellFilled,
  IconBolt,
  IconBoltFilled,
  IconBook,
  IconBookFilled,
  IconBrain,
  IconBraces,
  IconBrandDocker,
  IconBrandGithub,
  IconBrandGithubFilled,
  IconBrandPython,
  IconBrandReact,
  IconBrandVscode,
  IconBug,
  IconBugFilled,
  IconChartBar,
  IconChecklist,
  IconClockFilled,
  IconCloud,
  IconCloudFilled,
  IconCode,
  IconCommand,
  IconCpu,
  IconDatabase,
  IconDatabaseFilled,
  IconDeviceDesktop,
  IconDeviceDesktopFilled,
  IconDeviceLaptop,
  IconDownload,
  IconDownloadFilled,
  IconFileCodeFilled,
  IconFileDiffFilled,
  IconFileSearch,
  IconFileText,
  IconFileTextFilled,
  IconFlask,
  IconFlaskFilled,
  IconFolder,
  IconFolderFilled,
  IconFolderOpenFilled,
  IconGitBranch,
  IconGitCommit,
  IconGitMerge,
  IconGitPullRequest,
  IconKeyFilled,
  IconLayoutDashboardFilled,
  IconLink,
  IconLockFilled,
  IconMessageCircleFilled,
  IconPackage,
  IconPencilCode,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconRefresh,
  IconRobot,
  IconRoute,
  IconRocket,
  IconServer,
  IconSearch,
  IconSearchFilled,
  IconSettings,
  IconSettingsFilled,
  IconShieldSearch,
  IconSparkles,
  IconSparklesFilled,
  IconStackFilled,
  IconTerminal2,
  IconTestPipe,
  IconTool,
  IconUpload,
  IconWand,
  IconWorld,
} from "@tabler/icons-react";
import {
  getSidebarCommandIconLabel,
  SIDEBAR_COMMAND_ICON_IDS,
  type SidebarCommandIcon,
} from "../shared/sidebar-command-icons";

type TablerIconProps = {
  className?: string;
  color?: string;
  size?: number;
  stroke?: number;
};

const ICON_COMPONENT_BY_ID: Record<SidebarCommandIcon, ComponentType<TablerIconProps>> = {
  api: IconApi,
  archive: IconArchiveFilled,
  bell: IconBellFilled,
  bolt: IconBoltFilled,
  book: IconBookFilled,
  brain: IconBrain,
  braces: IconBraces,
  brandDocker: IconBrandDocker,
  brandGithub: IconBrandGithubFilled,
  brandPython: IconBrandPython,
  brandReact: IconBrandReact,
  brandVscode: IconBrandVscode,
  bug: IconBugFilled,
  chartBar: IconChartBar,
  checklist: IconChecklist,
  clock: IconClockFilled,
  cloud: IconCloudFilled,
  code: IconCode,
  command: IconCommand,
  cpu: IconCpu,
  database: IconDatabaseFilled,
  deviceDesktop: IconDeviceDesktopFilled,
  deviceLaptop: IconDeviceLaptop,
  download: IconDownloadFilled,
  fileCode: IconFileCodeFilled,
  fileDiff: IconFileDiffFilled,
  fileSearch: IconFileSearch,
  fileText: IconFileTextFilled,
  flask: IconFlaskFilled,
  folder: IconFolderFilled,
  folderOpen: IconFolderOpenFilled,
  gitBranch: IconGitBranch,
  gitCommit: IconGitCommit,
  gitMerge: IconGitMerge,
  gitPullRequest: IconGitPullRequest,
  key: IconKeyFilled,
  layoutDashboard: IconLayoutDashboardFilled,
  link: IconLink,
  lock: IconLockFilled,
  messageCircle: IconMessageCircleFilled,
  package: IconPackage,
  pencilCode: IconPencilCode,
  playerPlay: IconPlayerPlayFilled,
  refresh: IconRefresh,
  robot: IconRobot,
  route: IconRoute,
  rocket: IconRocket,
  search: IconSearchFilled,
  server: IconServer,
  settings: IconSettingsFilled,
  shieldSearch: IconShieldSearch,
  sparkles: IconSparklesFilled,
  stack: IconStackFilled,
  terminal: IconTerminal2,
  testPipe: IconTestPipe,
  tool: IconTool,
  upload: IconUpload,
  wand: IconWand,
  world: IconWorld,
};

export const SIDEBAR_COMMAND_ICON_OPTIONS = SIDEBAR_COMMAND_ICON_IDS.map((icon) => ({
  icon,
  label: getSidebarCommandIconLabel(icon),
}));

export type SidebarCommandIconGlyphProps = {
  className?: string;
  color?: string;
  icon: SidebarCommandIcon;
  size?: number;
  stroke?: number;
};

export function SidebarCommandIconGlyph({
  className,
  color,
  icon,
  size = 15,
  stroke = 1.8,
}: SidebarCommandIconGlyphProps) {
  const Icon = ICON_COMPONENT_BY_ID[icon];
  return (
    <Icon aria-hidden="true" className={className} color={color} size={size} stroke={stroke} />
  );
}
